#Setting logging levels
logging:
  level:
    org.springframework.web: WARN
    com.cts: DEBUG
    
#Enable the H2 database
spring:
 h2.console.enabled: true
 h2.console.path: /h2
 jpa:
  properties:
   hibernate.show_sql: true
  hibernate:
    ddl-auto: none
server:
 port: 8089    
 